jtype: Flow                                       # we define the Flow used for storing (CRUD operations)
version: '1'
with:
  protocol: http                                  # we want to use the REST HTTP API
  port_expose: 9000                               # the port to listen on. This is referenced in `app.py`
executors:                                        # the components in this Flow
  - name: storage_encoder                         # the name. This is the Encoder (transforms the text into vectors)
    uses: jinahub+docker://TransformerSentenceEncoder       # we use a pre-built Executor docker image
    uses_with:
      model_name: 'distiluse-base-multilingual-cased-v1'
      batch_size: 32
      device: 'cpu'
    timeout_ready: -1                             # disable timing out on startup (downloading image can take some time)
    timeout_ctrl: -1
  - name: storage_indexer                         # the name. This stores the data in an LMDB db
    uses: jinahub+docker://LMDBStorage            # again, we use a docker image
    timeout_ready: -1                             # disable startup
    timeout_ctrl: -1
    volumes: $JINAD_WORKSPACE:/jinad_workspace    # workspace where the file will be stored